#bash experiments/experiment_specifications/GenericBanditRunner/generic_adversarial.sh
#bash experiments/experiment_specifications/GenericBanditRunner/generic_movielens.sh
#bash experiments/experiment_specifications/TsallisExperiments/run_tsallis.sh
#bash experiments/experiment_specifications/TsallisExperiments/run_tsallis_exp3m.sh
bash experiments/experiment_specifications/TsallisExperiments/run_tsallis_exp3.sh