#bash experiments/experiment_specifications/GenericBanditRunner/generic_adversarial.sh
#bash experiments/experiment_specifications/GenericBanditRunner/generic_movielens.sh
#bash experiments/experiment_specifications/AdversarialExperiments/run_adversarial.sh
bash experiments/experiment_specifications/AdversarialExperiments/run_adversarial_exp3m.sh


