bash experiments/experiment_specifications/GenericBanditRunner/generic_adversarial.sh
#bash experiments/experiment_specifications/GenericBanditRunner/generic_movielens.sh
#bash experiments/experiment_specifications/TsallisExperiments/run_tsallis.sh